build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.22"
  amd64: "ghcr.io/home-assistant/amd64-base:3.22"
  armhf: "ghcr.io/home-assistant/armhf-base:3.22"
  armv7: "ghcr.io/home-assistant/armv7-base:3.22"
  i386: "ghcr.io/home-assistant/i386-base:3.22"
labels:
  org.opencontainers.image.title: "Home Assistant App: Ebusd"
  org.opencontainers.image.description: "This App runs eBUSd, a daemon for handling communication with eBUS devices"
  org.opencontainers.image.source: "https://github.com/bananafunction/ha-ebusd-app"
  org.opencontainers.image.licenses: "Apache License 2.0"
